/* ============================================================================
 * generate.js — dot placement, plus the two renderers.
 *
 * A preset's density is read as a HEIGHT SURFACE, not as a mask over a fixed
 * lattice. Rows of points run across the frame in the flow direction, and each
 * point is pushed perpendicular to its row by the height of the form beneath
 * it. So the rows ripple into the shape the preset describes, and the dots sit
 * on those waves. Height also drives dot size and density, so light still
 * carries the depth.
 *
 * Rows are generated across the frame's rotated bounding box and clipped to
 * the frame, so turning the angle lets the pattern bleed off every edge
 * instead of being contained by it.
 * ==========================================================================*/
var DG = window.DG || (window.DG = {});

(function (DG) {
  'use strict';

  DG.ASPECT = 16 / 9;

  DG.DEFAULTS = {
    preset: 'emergence',
    pointDensity: 30,     // points across the height of the frame
    patternScale: 1,      // size of one copy of the form, against frame height
    repeat: 'single',     // single, or one of the wallpaper groups below
    softness: 0.25,       // blurs the form, so its edges and seams stay smooth
    waveHeight: 0.55,     // how far the form displaces its rows
    waveMode: 'ridge',    // ridge (rows ride over the surface) | bulge (rows open around it)
    hideBehind: true,     // hold crowded rows apart rather than dropping them
    dotScale: 0.72,       // largest dot as a fraction of the point spacing
    sizeVariation: 0.85,  // extent of the difference between small and large dots
    contrast: 1.0,        // gamma on the height before it becomes size
    densityFade: 0.2,     // how much the field thins the points out
    flowAngle: 0,         // degrees — the direction the rows run
    flowStrength: 0,      // drift along the preset's own field lines
    seed: 1,
    colorMode: 'red',     // a solid id, or 'gradient'
    gradientMap: 'intensity',
    gradientReverse: false,
    background: 'black',
    // Image mode
    // 'replace' takes the whole height from the picture, which leaves the form
    // contributing nothing and renders all twelve presets identically. Half and
    // half keeps the form in the result.
    imageBlend: 'average', // average | multiply | replace
    imageInvert: false,
    imageDistort: 0.5,    // how hard the form's shape bends the picture
    imageAmount: 1
  };

  var FLOW_STEPS = 6;
  var TAU = Math.PI * 2;
  var ROOT3 = Math.sqrt(3);

  /*
   * The wallpaper groups. Rather than stamping copies out, a point is folded
   * into the group's fundamental domain before the form is read — so the form
   * is repeated under that group's own symmetries, mirrors and glides and
   * rotations included, and the result is a genuine plane pattern rather than a
   * grid of duplicates.
   *
   * Coordinates are the form's own, with the lattice cell spanning -1..1, so
   * the symmetry centre sits on the middle of the form.
   */
  DG.WALLPAPER = [
    { id: 'single', label: 'One copy' },
    { id: 'p1', label: 'p1 — plain repeat' },
    { id: 'p2', label: 'p2 — half turns' },
    { id: 'pm', label: 'pm — mirrored' },
    { id: 'pg', label: 'pg — glide reflected' },
    { id: 'pmm', label: 'pmm — mirrored both ways' },
    { id: 'pgg', label: 'pgg — two glides' },
    { id: 'p4', label: 'p4 — quarter turns' },
    { id: 'p4m', label: 'p4m — quarter turns, mirrored' },
    { id: 'p3', label: 'p3 — third turns, hexagonal' },
    { id: 'p6', label: 'p6 — sixth turns, hexagonal' },
    { id: 'p6m', label: 'p6m — sixth turns, mirrored' }
  ];

  /* Back into the cell, which spans -1..1. */
  function wrapCell(v) {
    var t = (v + 1) % 2;
    if (t < 0) t += 2;
    return t - 1;
  }

  /*
   * Onto the hexagonal lattice generated by (2, 0) and (1, root 3), reduced to
   * the cell nearest the origin. Reducing to the rhombus is not enough: a
   * rhombus is not six-fold symmetric, so two equivalent points could land
   * either side of it and a rotation fold after it would not be canonical.
   * Taking the closest of the seven candidate cells gives the hexagonal cell,
   * which does carry the rotation.
   */
  var HEX_NEIGHBOURS = [[0, 0], [2, 0], [-2, 0], [1, ROOT3], [-1, ROOT3], [1, -ROOT3], [-1, -ROOT3]];

  function wrapHex(s, t) {
    var n = t / ROOT3;
    var m = (s - n) / 2;
    m -= Math.round(m);
    n -= Math.round(n);
    var x = 2 * m + n;
    var y = n * ROOT3;
    var bx = x;
    var by = y;
    var best = x * x + y * y;
    for (var i = 1; i < HEX_NEIGHBOURS.length; i++) {
      var cx = x - HEX_NEIGHBOURS[i][0];
      var cy = y - HEX_NEIGHBOURS[i][1];
      var d = cx * cx + cy * cy;
      if (d < best - 1e-12) {
        best = d;
        bx = cx;
        by = cy;
      }
    }
    return [bx, by];
  }

  /* Into one wedge of an n-fold rotation about the centre. */
  function foldRot(s, t, n) {
    var step = TAU / n;
    var k = Math.round(Math.atan2(t, s) / step);
    if (!k) return [s, t];
    var c = Math.cos(-k * step);
    var q = Math.sin(-k * step);
    return [s * c - t * q, s * q + t * c];
  }

  /*
   * Each group as its own set of operations, modulo the lattice. The pattern is
   * the strongest of a point's images under them.
   *
   * Folding a point down into a fundamental domain is the textbook move, and it
   * is exactly right for a motif drawn to fill that domain. These forms are not
   * — they fill the whole cell — so folding read only the slice of a form that
   * fell inside the wedge and threw the rest away, which left the rotation
   * groups all but empty. Taking the orbit instead replicates the whole form,
   * and is just as invariant: a group element only permutes a point's images,
   * so the strongest of them does not move.
   */
  function rotOp(a) {
    var c = Math.cos(a);
    var q = Math.sin(a);
    return function (s, t) { return [s * c - t * q, s * q + t * c]; };
  }

  function mirrorY(op) {
    return function (s, t) { var p = op(s, t); return [p[0], -p[1]]; };
  }

  var ID = function (s, t) { return [s, t]; };
  var ROT = [0, 1, 2, 3, 4, 5].map(function (k) { return rotOp((k * TAU) / 6); });
  var QUARTER = [0, 1, 2, 3].map(function (k) { return rotOp((k * TAU) / 4); });

  var GROUP_OPS = {
    p1: [ID],
    p2: [ID, function (s, t) { return [-s, -t]; }],
    pm: [ID, function (s, t) { return [-s, t]; }],
    pg: [ID, function (s, t) { return [-s, t + 1]; }],
    pmm: [ID, function (s, t) { return [-s, t]; }, function (s, t) { return [s, -t]; },
      function (s, t) { return [-s, -t]; }],
    // The two glides compose to a half turn about the corner of the quarter
    // cell, not the middle of it.
    pgg: [ID, function (s, t) { return [-s, t + 1]; }, function (s, t) { return [s + 1, -t]; },
      function (s, t) { return [1 - s, -1 - t]; }],
    p4: QUARTER,
    p4m: QUARTER.concat(QUARTER.map(mirrorY)),
    p3: [ROT[0], ROT[2], ROT[4]],
    p6: ROT,
    p6m: ROT.concat(ROT.map(mirrorY))
  };

  var HEX_GROUPS = { p3: 1, p6: 1, p6m: 1 };

  DG.groupOps = GROUP_OPS;

  /* Deterministic per-point noise, so a given seed always redraws identically. */
  function hash2(i, j, seed) {
    var h = Math.imul(i, 0x27d4eb2d) + Math.imul(j, 0x165667b1) + Math.imul(seed, 0x9e3779b1);
    h = Math.imul(h ^ (h >>> 15), 0x2c1b3c6d);
    h = Math.imul(h ^ (h >>> 12), 0x297a2d39);
    h ^= h >>> 15;
    return (h >>> 0) / 4294967296;
  }

  /*
   * Build the dot list for a frame of `width` x `height` pixels.
   *
   * `sampler(u, v) -> 0..1` is the optional image source, addressed in frame
   * coordinates (0..1 across the whole frame, never tiled) so a photograph
   * stays put while the form repeats beneath it.
   */
  DG.generateDots = function (params, width, height, sampler) {
    var p = Object.assign({}, DG.DEFAULTS, params);
    var preset = DG.getPreset(p.preset);

    var spacing = height / Math.max(2, p.pointDensity);
    var half = (height * Math.max(0.05, p.patternScale)) / 2;  // half a copy of the form
    var amp = p.waveHeight * half;                              // displacement in px
    var maxR = (spacing / 2) * p.dotScale;
    var cx = width / 2;
    var cy = height / 2;

    var th = (p.flowAngle * Math.PI) / 180;
    var cos = Math.cos(th);
    var sin = Math.sin(th);

    // Cover the frame's rotated bounding box, with room for the displacement.
    var reach = Math.hypot(width, height) / 2 + amp + spacing * 2;
    var steps = Math.ceil(reach / spacing);

    var ramp = DG.buildRamp();
    var useGradient = p.colorMode === 'gradient';
    var drift = (p.flowStrength * (spacing / half) * 3) / FLOW_STEPS;

    var group = p.repeat;
    var tiled = group && group !== 'single';
    var blur = Math.max(0, p.softness) * 0.3;

    var ops = tiled ? GROUP_OPS[group] || GROUP_OPS.p1 : null;
    var hex = tiled && HEX_GROUPS[group];

    function toCell(s, t) {
      return hex ? wrapHex(s, t) : [wrapCell(s), wrapCell(t)];
    }

    /* The form, repeated under the group. */
    function motifAt(fx, fy) {
      if (!tiled) return preset.density(fx, fy);
      var p0 = toCell(fx, fy);
      var best = 0;
      for (var i = 0; i < ops.length; i++) {
        var q = ops[i](p0[0], p0[1]);
        q = toCell(q[0], q[1]);
        var d = preset.density(q[0], q[1]);
        if (d > best) best = d;
      }
      return best;
    }

    DG.probeMotif = motifAt;

    /*
     * Softened. Five taps rather than one, so an edge in the form and the seam
     * where one copy meets the next both come out smooth instead of hard.
     */
    function formAt(fx, fy) {
      if (blur <= 0) return motifAt(fx, fy);
      return (
        motifAt(fx, fy) * 2 +
        motifAt(fx + blur, fy) +
        motifAt(fx - blur, fy) +
        motifAt(fx, fy + blur) +
        motifAt(fx, fy - blur)
      ) / 6;
    }

    /* Frame pixel -> the form's own coordinates. */
    function toField(x, y) {
      return [(x - cx) / half, (y - cy) / half];
    }

    /*
     * How far the form pushes the picture around, calibrated against how steep
     * this preset actually gets at this scale so the control behaves the same
     * whatever is loaded.
     */
    var distort = sampler ? Math.max(0, p.imageDistort) : 0;
    var gEps = 0.05;
    var maxPush = 0.22 * Math.min(width, height);
    var gRef = 1e-4;
    if (distort > 0) {
      var slopes = [];
      for (var sy = 0; sy < 10; sy++) {
        for (var sx = 0; sx < 10; sx++) {
          var qx = (-1 + (2 * (sx + 0.5)) / 10) * (width / 2 / half);
          var qy = (-1 + (2 * (sy + 0.5)) / 10) * (height / 2 / half);
          slopes.push(Math.hypot(
            formAt(qx + gEps, qy) - formAt(qx - gEps, qy),
            formAt(qx, qy + gEps) - formAt(qx, qy - gEps)
          ));
        }
      }
      slopes.sort(function (a, b) { return a - b; });
      gRef = Math.max(1e-4, slopes[Math.floor(slopes.length * 0.9)]);
    }

    function heightAt(fx, fy, x, y) {
      var base = formAt(fx, fy);
      if (!sampler) return base;

      /*
       * The form works as a displacement map: the picture is read from a point
       * pushed along the form's slope, so it stretches down the flanks and
       * gathers at the crests. Each preset bends the same photograph its own
       * way, which is where the textures come from — blending two heights
       * together could never do that.
       */
      var sxp = x;
      var syp = y;
      if (distort > 0) {
        var gx = formAt(fx + gEps, fy) - formAt(fx - gEps, fy);
        var gy = formAt(fx, fy + gEps) - formAt(fx, fy - gEps);
        var len = Math.hypot(gx, gy);
        if (len > 1e-9) {
          var push = Math.min(1, len / gRef) * distort * maxPush;
          sxp += (gx / len) * push;
          syp += (gy / len) * push;
        }
      }
      var img = sampler(sxp / width, syp / height);
      if (p.imageInvert) img = 1 - img;
      var v;
      if (p.imageBlend === 'multiply') v = img * base;
      else if (p.imageBlend === 'average') v = (img + base) / 2;
      else v = img;
      return DG.clamp01(base + (v - base) * p.imageAmount);
    }

    var dots = [];
    var margin = maxR + 1;

    // Horizon per column. Rows are walked front to back, and where the form is
    // too steep for the row spacing the row behind is held back to keep a gap
    // rather than being dropped. Dropping it cut a hard silhouette and packed
    // the crest into a flat cap; holding it back rounds the crest over and every
    // point stays on the page.
    var relax = p.hideBehind && p.waveMode === 'ridge' && amp !== 0;
    var horizon = relax ? new Float64Array(2 * steps + 1).fill(Infinity) : null;
    var minGap = spacing * 0.62;

    for (var jv = steps; jv >= -steps; jv--) {
      var v = jv * spacing;                    // which row
      for (var iu = -steps; iu <= steps; iu++) {
        var u = iu * spacing;                  // position along the row

        // Base position of the point on its undisplaced row.
        var x = cx + u * cos - v * sin;
        var y = cy + u * sin + v * cos;

        var f = toField(x, y);
        var fx = f[0];
        var fy = f[1];

        // Optional drift along the preset's own field lines.
        if (drift !== 0) {
          for (var s = 0; s < FLOW_STEPS; s++) {
            var a = DG.flowAt(preset, fx, fy) + th;
            fx += Math.cos(a) * drift;
            fy += Math.sin(a) * drift;
          }
          x = cx + fx * half;
          y = cy + fy * half;
        }

        var raw = DG.clamp01(heightAt(fx, fy, x, y));
        var hgt = Math.pow(raw, p.contrast);

        // Push the point out of its row by the height of the form beneath it,
        // along the row's normal. In bulge mode rows open away from the form's
        // mid-line so the volume stays centred; in ridge mode every row lifts
        // the same way, like a contour map.
        if (amp !== 0) {
          var d;
          if (p.waveMode === 'ridge') {
            // Measured from mid-height, so the form straddles its rows instead
            // of piling the whole pattern to one side. Eased, so the wave rolls
            // over its crest rather than driving straight into it.
            var e = hgt * hgt * (3 - 2 * hgt);
            d = -(e - 0.5) * amp;
          } else {
            var side = -(x - cx) * sin + (y - cy) * cos;   // offset along the normal
            d = (side < 0 ? -1 : 1) * hgt * amp;
          }
          x += -sin * d;
          y += cos * d;

          if (relax) {
            var col = iu + steps;
            var vDisp = v + d;                 // where the row sits after displacing
            var limit = horizon[col] - minGap;
            if (vDisp > limit) {
              // Too close to the row in front: ease it back to the gap.
              var pull = vDisp - limit;
              x -= -sin * pull;
              y -= cos * pull;
              vDisp = limit;
            }
            horizon[col] = vDisp;
          }
        }

        // Clip to the frame: the pattern bleeds off the edges.
        if (x < -margin || x > width + margin || y < -margin || y > height + margin) continue;

        // Density: the darker the field, the more likely the point is dropped.
        var keep = 1 - p.densityFade * (1 - hgt);
        if (hash2(iu, jv, p.seed + 7717) > keep) continue;

        var r = maxR * (1 - p.sizeVariation + p.sizeVariation * hgt);
        if (r < 0.12) continue;

        var dot = { x: x, y: y, r: r, v: hgt, nx: (x - cx) / (width / 2), ny: (y - cy) / (height / 2) };
        if (useGradient) {
          var t = DG.gradientCoord(p.gradientMap, dot);
          if (p.gradientReverse) t = 1 - t;
          dot.color = ramp[Math.min(ramp.length - 1, Math.max(0, Math.round(t * (ramp.length - 1))))];
        }
        dots.push(dot);
      }
    }
    return dots;
  };

  /* Paint the dots onto a 2D context already sized in logical pixels. */
  DG.renderDots = function (ctx, dots, opts) {
    ctx.save();
    ctx.clearRect(0, 0, opts.width, opts.height);
    if (opts.background) {
      ctx.fillStyle = opts.background;
      ctx.fillRect(0, 0, opts.width, opts.height);
    }
    if (!opts.useGradient) ctx.fillStyle = opts.solid;
    for (var i = 0; i < dots.length; i++) {
      var d = dots[i];
      if (opts.useGradient) ctx.fillStyle = d.color;
      ctx.beginPath();
      ctx.arc(d.x, d.y, d.r, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.restore();
  };

  /* Same drawing, as a standalone SVG document. */
  DG.dotsToSVG = function (dots, opts) {
    var body = dots.map(function (d) {
      return '<circle cx="' + d.x.toFixed(2) + '" cy="' + d.y.toFixed(2) + '" r="' + d.r.toFixed(2) + '"' +
        (opts.useGradient ? ' fill="' + d.color + '"' : '') + '/>';
    }).join('');
    return [
      '<svg xmlns="http://www.w3.org/2000/svg" width="' + opts.width + '" height="' + opts.height +
        '" viewBox="0 0 ' + opts.width + ' ' + opts.height + '">',
      opts.background ? '<rect width="' + opts.width + '" height="' + opts.height + '" fill="' + opts.background + '"/>' : '',
      '<g' + (opts.useGradient ? '' : ' fill="' + opts.solid + '"') + '>' + body + '</g>',
      '</svg>'
    ].join('');
  };
})(DG);
